name: Compile Sass

on:
  push:
    branches: [main] # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Sass globally
        run: npm install -g sass

      - name: Compile Sass
        run: sass src/scss:dist --style=compressed --no-source-map

      - name: Commit & Push compiled CSS
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "felixthecat8a"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git add dist
          git diff --staged --quiet || git commit -m "chore: update compiled CSS [skip ci]"
          git push origin HEAD:${{ github.ref_name }}
