name: Compile Less

on:
  push:
    branches: [main]
    paths:
      - 'src/less/**/*.less'
  pull_request:
    paths:
      - 'src/less/**/*.less'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Less
        run: npm install less

      - name: Clean old CSS files
        run: |
          mkdir -p dist/css
          rm -f dist/css/*.css

      - name: Compile Less
        run: npx lessc src/less/style.less dist/css/style.css

      - name: Commit & Push compiled CSS
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "felixthecat8a"
          git config user.email "felixthecat8a@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT}@github.com/${{ github.repository }}"
          git add dist/css
          git diff --staged --quiet || git commit -m "chore: update compiled CSS"
          git push origin HEAD:${{ github.ref_name }}
